DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS trips;


CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  first_name VARCHAR,
  last_name VARCHAR,
  home_zip INT
);

CREATE TABLE trips (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
creator_id BIGINT NOT NULL,
location VARCHAR NOT NULL,
url VARCHAR NOT NULL,
foreign key (creator_id) references users(id)
);